FROM rocker/verse:4.1.0
RUN apt-get update && apt-get install -y \
    libv8-dev \
    libudunits2-dev \
    liblzma-dev \
    libbz2-dev \
    git-all \
    python3-dev \
    python3-pip \
    libhdf5-dev

#### R packages ####

RUN R -e "install.packages(c('BiocManager'))"
RUN R -e "BiocManager::install(c('GEOquery', 'quantiseqr'))"
RUN R -e "install.packages(c('ggplot2','data.table','Seurat','Matrix','ggpubr','R.utils'))"
#RUN R -e "BiocManager::install(c('monocle'))"
RUN R -e "BiocManager::install(c('BiocGenerics', 'DelayedArray', 'DelayedMatrixStats', 'limma', 'S4Vectors', 'SingleCellExperiment','SummarizedExperiment', 'batchelor', 'Matrix.utils','Rcpp'))"
RUN R -e "install.packages('devtools')"
RUN R -e "devtools::install_github('cole-trapnell-lab/leidenbase')"
RUN R -e "devtools::install_github('cole-trapnell-lab/monocle3')"
RUN R -e "remotes::install_github('mojaveazure/seurat-disk')"
RUN R -e "install.packages(c('remotes','stringi','hdf5r','rlang','cli','crayon'))"
RUN R -e "BiocManager::install(c('DropletUtils','BUSpaRse'))"
#RUN R -e "remotes::install_github('mojaveazure/seurat-disk')"


#### python packages ####
RUN pip install numpy
RUN pip install simhash
RUN pip install keras
RUN pip install sklearn
RUN pip install pandas
RUN pip install Bio

WORKDIR /home

CMD ["/bin/bash"]

# docker run --rm -it -v /nfs/home/students/adietrich/ma/data/:/home/data -v /nfs/home/students/adietrich/ma/simulator/:/home/simulator -v /nfs/home/students/adietrich/ma/toolsAndIdx:/home/toolsAndIdx deconv_simulator
